### PR TITLE
refactor: replace QLC with plain `ets:select/{1,3}`

### PR DESCRIPTION
**Pull request by hauleth**
This should remove requirement for indirection that happen with QLC
process and should reduce need for additional data copy between QLC and
target process.

### CODE REVIEW

**Comment by hauleth** [comment]
Does Cachix need to still support Elixir 1.7-1.9? These versions are long not supported.

**Comment by whitfin** [comment]
Hi @hauleth!

Yes, Cachex will continue to support v1.7+ (technically it supports back to v1.5 even!). In this case `Function.identity/1` provides such minimal value that it's not worth changing the compatibility table for. 

That being said this PR seems good (if that's updated) and I'm happy to merge and include in the next release!

**Comment by hauleth** [comment]
@whitfin done. Also - I hope that you are hefty compensated for keeping that compatibility with so old Elixir releases.

**Comment by whitfin** [comment]
Awesome, ty @hauleth - just so you know this is all good to go, I'm just holding on merging because I want to land this alongside a fix for #329 to remove all QLC in one sweep.

**Pull request merged**
