### PR TITLE
Fixes warnings for Elixir 1.11

### PR DESCRIPTION
**Pull request by sezaru**
This PR fixes all warnings in Cachex when using Elixir 1.11

### CODE REVIEW

**Comment by jlgeering** [comment]
@sezaru do your changes drop compatibility for Elixir < 1.5 (based on the travis test results)?

**Comment by sezaru** [comment]
Yeah, seems like that `Supervisor.init/2` was introduced in elixir 1.5

**Comment by whitfin** [comment]
Thanks for the PR! Linking it over to #269 as this is not viable on older versions until we bump the minimum version.

Does anyone have a suggestion for what the minimum should be these days? Is v1.5+ viable?

**Comment by whitfin** [comment]
This has been included in the bundle commit of https://github.com/whitfin/cachex/commit/757249fde1c0d31198948b3f6960ae02ac2ec3d4 - thanks for your changes :) 🚀

**Pull request closed without merging**
