### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by MasashiYokota**
Thank you for this awesome project. 

I've found that a part of README about `Usage` is a little out-of-date.
I've fixed the README based on [this post of Elixir Forum](https://elixirforum.com/t/how-to-run-more-then-one-same-worker-cachex-inside-supervision/14911/3).

If you know other better ways about this or have any questions, please give me some comments.
Thank you.

### CODE REVIEW

**Comment by whitfin** [comment]
Hi @MasashiYokota!

I'm fine with this, but I would like to keep the old example, since it's still valid. Maybe you can change it to something like this:


The typical use of Cachex is to set up using a Supervisor, so that it can be handled automatically:

```elixir
Supervisor.start_link(
  [
    %{
      id: :my_cache_id,
      start: {Cachex, :start_link, [:my_cache, []]}
    }
  ]
)
```
If you are using Elixir versions prior to Elixir v1.5, you are able use the older syntax:

```elixir
Supervisor.start_link(
  [ worker(Cachex, [:my_cache, []]) ]
)
```

**Comment by MasashiYokota** [comment]
@whitfin 
Thank you for your comment. 
I've modified README. Please confirm it.

**Comment by MasashiYokota** [comment]
@whitfin 
I understand you are very busy, but I'm glad if you confirm my PR.

**Comment by krainboltgreene** [comment]
@whitfin How can I help get this published?

**Pull request merged**
